<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Putting-It-All-Together-The-Java-Tutorials---------------------Essential-Classes--Exceptions.html</title></head>
<body>
<h1>Putting It All Together</h1>
<p>The previous sections described how to construct the <code>try</code>, <code>catch</code>, and <code>finally</code> code blocks for the <code>writeList</code> method in the <code>ListOfNumbers</code> class. Now, let's walk through the code and investigate what can happen.</p>
<p>When all the components are put together, the <code>writeList</code> method looks like the following.</p>
<p>WHATSON? 475f9ac2-d440-4775-993a-489b7b433372</p>
<pre>
public void writeList() {
    PrintWriter out = null;

    try {
        System.out.println("Entering" + " try statement");

        out = new PrintWriter(new FileWriter("OutFile.txt"));
        for (int i = 0; i &lt; SIZE; i++) {
            out.println("Value at: " + i + " = " + list.get(i));
        }
    } catch (IndexOutOfBoundsException e) {
        System.err.println("Caught IndexOutOfBoundsException: "
                           +  e.getMessage());
                                 
    } catch (IOException e) {
        System.err.println("Caught IOException: " +  e.getMessage());
                                 
    } finally {
        if (out != null) {
            System.out.println("Closing PrintWriter");
            out.close();
        } 
        else {
            System.out.println("PrintWriter not open");
        }
    }
}
</pre>
<p>As mentioned previously, this method's <code>try</code> block has three different exit possibilities; here are two of them.</p>
<ol>
<li>Code in the <code>try</code> statement fails and throws an exception. This could be an <code>IOException</code> caused by the <code>new FileWriter</code> statement or an <code>IndexOutOfBoundsException</code> caused by a wrong index value in the <code>for</code> loop.</li>
<li>Everything succeeds and the <code>try</code> statement exits normally.</li>
</ol>
<p>Let's look at what happens in the <code>writeList</code> method during these two exit possibilities.</p>
<h2>Scenario 1: An Exception Occurs</h2>
<p>The statement that creates a <code>FileWriter</code> can fail for a number of reasons. For example, the constructor for the <code>FileWriter</code> throws an <code>IOException</code> if the program cannot create or write to the file indicated.</p>
<p>When <code>FileWriter</code> throws an <code>IOException</code>, the runtime system immediately stops executing the <code>try</code> block; method calls being executed are not completed. The runtime system then starts searching at the top of the method call stack for an appropriate exception handler. In this example, when the <code>IOException</code> occurs, the <code>FileWriter</code> constructor is at the top of the call stack. However, the <code>FileWriter</code> constructor doesn't have an appropriate exception handler, so the runtime system checks the next method  the <code>writeList</code> method  in the method call stack. The <code>writeList</code> method has two exception handlers: one for <code>IOException</code> and one for <code>IndexOutOfBoundsException</code>.</p>
<p>The runtime system checks <code>writeList</code>'s handlers in the order in which they appear after the <code>try</code> statement. The argument to the first exception handler is <code>IndexOutOfBoundsException</code>. This does not match the type of exception thrown, so the runtime system checks the next exception handler  <code>IOException</code>. This matches the type of exception that was thrown, so the runtime system ends its search for an appropriate exception handler. Now that the runtime has found an appropriate handler, the code in that <code>catch</code> block is executed.</p>
<p>After the exception handler executes, the runtime system passes control to the <code>finally</code> block. Code in the <code>finally</code> block executes regardless of the exception caught above it. In this scenario, the <code>FileWriter</code> was never opened and doesn't need to be closed. After the <code>finally</code> block finishes executing, the program continues with the first statement after the <code>finally</code> block.</p>
<p>Here's the complete output from the <code>ListOfNumbers</code> program that appears when an <code>IOException</code> is thrown.</p>
<p>WHATSON? 1015e018-09fe-4bef-beca-c927315b83d0</p>
<pre>
Entering try statement
Caught IOException: OutFile.txt
PrintWriter not open 
</pre>
<p>The boldface code in the following listing shows the statements that get executed during this scenario:</p>
<p>WHATSON? c63b525b-42dc-49b7-a2b5-3336162be14b</p>
<pre>
public void writeList() {
   <b>PrintWriter out = null;

    try {
        System.out.println("Entering try statement");
        out = new PrintWriter(new FileWriter("OutFile.txt"));</b>
        for (int i = 0; i &lt; SIZE; i++)
            out.println("Value at: " + i + " = " + list.get(i));
                               
    } catch (IndexOutOfBoundsException e) {
        System.err.println("Caught IndexOutOfBoundsException: "
                           + e.getMessage());
                                 
    } <b>catch (IOException e) {
        System.err.println("Caught IOException: " + e.getMessage());
    } finally {
        if (out != null) {</b>
            System.out.println("Closing PrintWriter");
            out.close();
        } 
        <b>else {
            System.out.println("PrintWriter not open");
        }</b>
    }
}
</pre>
<h2>Scenario 2: The try Block Exits Normally</h2>
<p>In this scenario, all the statements within the scope of the <code>try</code> block execute successfully and throw no exceptions. Execution falls off the end of the <code>try</code> block, and the runtime system passes control to the <code>finally</code> block. Because everything was successful, the <code>PrintWriter</code> is open when control reaches the <code>finally</code> block, which closes the <code>PrintWriter</code>. Again, after the <code>finally</code> block finishes executing, the program continues with the first statement after the <code>finally</code> block.</p>
<p>Here is the output from the <code>ListOfNumbers</code> program when no exceptions are thrown.</p>
<p>WHATSON? 9a1b0279-0a04-48d0-972c-42480bdf12dc</p>
<pre>
Entering try statement
Closing PrintWriter
</pre>
<p>The boldface code in the following sample shows the statements that get executed during this scenario.</p>
<p>WHATSON? 404ce60c-ae5c-4d7f-8992-2abe6c530019</p>
<pre>
public void writeList() {
    <b>PrintWriter out = null;
    try {
        System.out.println("Entering try statement");
        out = new PrintWriter(new FileWriter("OutFile.txt"));
        for (int i = 0; i &lt; SIZE; i++)
            out.println("Value at: " + i + " = " + list.get(i));
                  
    }</b> catch (IndexOutOfBoundsException e) {
        System.err.println("Caught IndexOutOfBoundsException: "
                           + e.getMessage());

    } catch (IOException e) {
        System.err.println("Caught IOException: " + e.getMessage());
                                 
    } <b>finally {
        if (out != null) {
            System.out.println("Closing PrintWriter");
            out.close();
        }</b> 
        else {
            System.out.println("PrintWriter not open");
        }
    }
}
</pre>
</body>
</html>